# generated by datamodel-codegen:
#   filename:  schema_converted.json
#   timestamp: 2025-07-14T14:25:02+00:00

from __future__ import annotations

from typing import List, Optional

from pydantic import BaseModel, Field


class AnnotationForm(BaseModel):
    Write_condition_of_patient: Optional[str] = Field(
        None, alias='Write condition of patient'
    )
    Symptoms: Optional[List[str]] = None
    High_Risk: Optional[str] = Field(None, alias='High Risk')
